-- Owner (Full Access)
CREATE ROLE 'owner';
GRANT ALL PRIVILEGES ON delola_store_db.* TO 'owner'; --placeholder database name

-- Employee
CREATE ROLE 'employee';
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDERS TO 'employee';
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDER_ITEM TO 'employee';
GRANT SELECT, INSERT, UPDATE, DELETE ON IN_STORE_ORDER TO 'employee';
GRANT SELECT, INSERT, UPDATE, DELETE ON DELIVERY_ORDER TO 'employee';
GRANT SELECT, INSERT, UPDATE, DELETE ON CUSTOMER TO 'employee';
GRANT SELECT, INSERT, UPDATE, DELETE ON DELIVERY TO 'employee';